env:
  browser: true
  es2021: true
extends: eslint:recommended
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
extends:
  - "airbnb-base"
  - "plugin:jest/recommended"
rules:
  no-console: 0
  import/extensions: 0
